# Generated by Django 4.1.4 on 2022-12-23 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='properties_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('completion_date', models.CharField(max_length=100)),
                ('Properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.properties')),
            ],
        ),
    ]
