# Generated by Django 4.1.4 on 2022-12-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_properties_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties_2',
            name='img',
        ),
        migrations.AddField(
            model_name='properties_2',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
